# export/ltspice.py
# Generates LTspice netlist files from filter component data

def generate_netlist(components, topology, response_type, order, fc, Z0):
    # Builds and returns a complete LTspice netlist as a string
    lines = []

    # Header
    lines.append(f'* {topology} Filter - {response_type} Order {order}')
    lines.append(f'* Cutoff: {fc:.1f} MHz   Z0: {Z0:.0f} ohm')
    lines.append(f'* Generated by RF Filter Designer')
    lines.append('')

    # 1V AC source and source resistance
    lines.append('V1 IN 0 AC 1')
    lines.append(f'RS IN N001 {Z0:.0f}')
    lines.append('')

    # Assign nodes to components
    # Series elements advance the node counter, shunt elements connect to ground
    node = 1
    inductor_count = 0
    capacitor_count = 0

    for comp in components:

        if comp['type'] == 'L':
            inductor_count += 1
            value_str = f"{comp['standard'] * 1e9:.3f}n"
            ref = f"L{inductor_count}"
        else:
            capacitor_count += 1
            value_str = f"{comp['standard'] * 1e12:.3f}p"
            ref = f"C{capacitor_count}"

        if comp['position'] == 'series':
            n_in  = f'N{node:03d}'
            n_out = f'N{node + 1:03d}'
            lines.append(f'{ref} {n_in} {n_out} {value_str}')
            node += 1
        elif comp['position'] == 'shunt':
            n_in = f'N{node:03d}'
            lines.append(f'{ref} {n_in} 0 {value_str}')

    lines.append('')

    # Load resistance at output node
    lines.append(f'RL N{node:03d} 0 {Z0:.0f}')
    lines.append('')

    # AC sweep from 1 MHz to 10 GHz, 1000 points per decade
    lines.append('.ac dec 1000 1Meg 10G')
    lines.append('.backanno')
    lines.append('.end')

    return '\n'.join(lines)


def save_netlist(filepath, components, topology, response_type, order, fc, Z0):
    # Generates the netlist and writes it to the specified filepath
    netlist = generate_netlist(components, topology, response_type, order, fc, Z0)
    with open(filepath, 'w') as f:
        f.write(netlist)


if __name__ == '__main__':
    from filters.lowpass import design_lowpass

    components = design_lowpass('butterworth', 3, fc=915e6, Z0=50)

    netlist = generate_netlist(components,
                               topology='Low-Pass',
                               response_type='Butterworth',
                               order=3,
                               fc=915.0,
                               Z0=50)
    print(netlist)